#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define RESOURCE_STORE (0)
#define RESOURCE_NEVER_STORE (1)

#define RESOURCE_STORE_POLICY RESOURCE_STORE

//#define DEBUG_WRITE_FBO
#define DEBUG_RENDER_WIREFRAME
